# Generated by Django 3.2.25 on 2025-12-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=10)),
                ('semester', models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester')], max_length=10)),
                ('branch', models.CharField(max_length=50)),
                ('subject_name', models.CharField(max_length=150)),
                ('exam_type', models.CharField(choices=[('mid1', 'Mid 1'), ('mid2', 'Mid 2'), ('sem', 'Semester'), ('supply', 'Supply')], max_length=20)),
                ('pdf_file', models.FileField(upload_to='question_papers/')),
            ],
        ),
    ]
