# Generated by Django 3.2.25 on 2025-12-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=2)),
                ('semester', models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester')], max_length=2)),
                ('branch', models.CharField(max_length=50)),
                ('subject_name', models.CharField(max_length=150)),
                ('notes_pdf', models.FileField(upload_to='notes_pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notes',
                'verbose_name_plural': 'Notes',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
