# Generated by Django 3.2.25 on 2025-12-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')])),
                ('semester', models.IntegerField(choices=[(1, '1st Semester'), (2, '2nd Semester')])),
                ('branch', models.CharField(max_length=50)),
                ('subject_name', models.CharField(max_length=100)),
                ('pdf_file', models.FileField(upload_to='syllabus_pdfs/')),
            ],
        ),
    ]
